//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Laboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Анализы__Tests_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Анализы__Tests_()
        {
            this.Результаты_анализов__Test_Results_ = new HashSet<Результаты_анализов__Test_Results_>();
        }
    
        public int Test_id { get; set; }
        public string name { get; set; }
        public int description_id { get; set; }
        public decimal price { get; set; }
    
        public virtual Описание_анализа__Description_ Описание_анализа__Description_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Результаты_анализов__Test_Results_> Результаты_анализов__Test_Results_ { get; set; }
    }
}
