//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Laboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Врачи__Doctors_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Врачи__Doctors_()
        {
            this.Назначения__Appointments_ = new HashSet<Назначения__Appointments_>();
            this.Результаты_анализов__Test_Results_ = new HashSet<Результаты_анализов__Test_Results_>();
        }
    
        public int Doctor_id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Specialization { get; set; }
        public string Email { get; set; }
        public string Phone_number { get; set; }
        public int Department { get; set; }
        public int Role { get; set; }
    
        public virtual Role Role1 { get; set; }
        public virtual Отделы__Departments_ Отделы__Departments_ { get; set; }
        public virtual Специализация_врача__Specialization_ Специализация_врача__Specialization_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Назначения__Appointments_> Назначения__Appointments_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Результаты_анализов__Test_Results_> Результаты_анализов__Test_Results_ { get; set; }
    }
}
