//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Телефонный_справочник
{
    using System;
    using System.Collections.Generic;
    
    public partial class Контакт
    {
        public int ID { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Номер_Телефона { get; set; }
        public string E_mail { get; set; }
        public Nullable<int> Компания { get; set; }
        public string Должность { get; set; }
        public Nullable<int> ID_Группа_контактов { get; set; }
        public Nullable<System.DateTime> Дата_Рождения { get; set; }
        public byte[] Фото { get; set; }
    
        public virtual Группа_контактов Группа_контактов { get; set; }
    }
}
