//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Laboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        public int Doctor_id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Specialization { get; set; }
        public string Email { get; set; }
        public string Phone_number { get; set; }
        public string Department { get; set; }
        public string Role { get; set; }
    }
}
