//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Laboratory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Medical_Laboratory_Entities : DbContext
    {
        public Medical_Laboratory_Entities()
            : base("name=Medical_Laboratory_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Анализы__Tests_> Анализы__Tests_ { get; set; }
        public virtual DbSet<Врачи__Doctors_> Врачи__Doctors_ { get; set; }
        public virtual DbSet<Закупки__Purchases_> Закупки__Purchases_ { get; set; }
        public virtual DbSet<Назначения__Appointments_> Назначения__Appointments_ { get; set; }
        public virtual DbSet<Оборудование__Equipment_> Оборудование__Equipment_ { get; set; }
        public virtual DbSet<Описание_анализа__Description_> Описание_анализа__Description_ { get; set; }
        public virtual DbSet<Отделы__Departments_> Отделы__Departments_ { get; set; }
        public virtual DbSet<Пациенты__Patients_> Пациенты__Patients_ { get; set; }
        public virtual DbSet<Поставщики__Suppliers_> Поставщики__Suppliers_ { get; set; }
        public virtual DbSet<Результаты_анализов__Test_Results_> Результаты_анализов__Test_Results_ { get; set; }
        public virtual DbSet<Специализация_врача__Specialization_> Специализация_врача__Specialization_ { get; set; }
        public virtual DbSet<Выставленые_счета_страховой_компании> Выставленые_счета_страховой_компании { get; set; }
        public virtual DbSet<Данные_страховых_компаний> Данные_страховых_компаний { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<Услуги_лаборатории> Услуги_лаборатории { get; set; }
    }
}
