//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Laboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Данные_страховых_компаний
    {
        public int id { get; set; }
        public string insurance_name { get; set; }
        public string country { get; set; }
        public string insurance_address { get; set; }
        public Nullable<int> insurance_inn { get; set; }
        public string ipadress { get; set; }
        public Nullable<int> insurance_p_c { get; set; }
        public Nullable<int> insurance_bik { get; set; }
    }
}
