//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Laboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Закупки__Purchases_
    {
        public int Purchase_id { get; set; }
        public int Supplier_id { get; set; }
        public int Equipment_id { get; set; }
        public System.DateTime Date_of_purchase { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual Оборудование__Equipment_ Оборудование__Equipment_ { get; set; }
        public virtual Поставщики__Suppliers_ Поставщики__Suppliers_ { get; set; }
    }
}
