//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Laboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int id { get; set; }
        public Nullable<int> patient { get; set; }
        public byte[] barcode { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public bool accepted { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> finished { get; set; }
        public Nullable<int> service { get; set; }
    }
}
