//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Laboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Назначения__Appointments_
    {
        public int Appointment_id { get; set; }
        public int Patient_id { get; set; }
        public int Doctor_id { get; set; }
        public System.DateTime Date_of_appointment { get; set; }
        public System.TimeSpan Time_of_appointment { get; set; }
        public string Reason { get; set; }
    
        public virtual Врачи__Doctors_ Врачи__Doctors_ { get; set; }
        public virtual Пациенты__Patients_ Пациенты__Patients_ { get; set; }
    }
}
