//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Laboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пациенты__Patients_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пациенты__Patients_()
        {
            this.Назначения__Appointments_ = new HashSet<Назначения__Appointments_>();
            this.Результаты_анализов__Test_Results_ = new HashSet<Результаты_анализов__Test_Results_>();
        }
    
        public int Patient_id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime Date_of_birth { get; set; }
        public string Address { get; set; }
        public string Phone_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Назначения__Appointments_> Назначения__Appointments_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Результаты_анализов__Test_Results_> Результаты_анализов__Test_Results_ { get; set; }
    }
}
