//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_Laboratory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги_лаборатории
    {
        public int id { get; set; }
        public string Наименование { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public string Срок_выполнения { get; set; }
        public Nullable<int> Среднее_отклонение { get; set; }
    }
}
